# Generated by Django 3.0.7 on 2020-07-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
