# Generated by Django 4.1.1 on 2022-10-09 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DepartmentId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('employeeName', models.CharField(max_length=100)),
                ('DateOfJoining', models.DateField()),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.department')),
            ],
        ),
    ]
