# Generated by Django 4.1.1 on 2022-10-09 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employeeName',
            new_name='EmployeeName',
        ),
    ]
