# Generated by Django 4.1.1 on 2022-10-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0002_rename_employeename_employee_employeename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Department',
            field=models.CharField(max_length=100),
        ),
    ]
