# Generated by Django 4.1.1 on 2022-11-11 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
    ]
