# Generated by Django 4.1.1 on 2022-11-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_title_todo_name_remove_todo_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'get_latest_by': ['']},
        ),
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
